version: '3.8'
services:
  rtsp-web:
    build: .
    container_name: rtsp-web
    ports:
      - "8083:8083"
    restart: unless-stopped
    network_mode: host  # Using host network to ensure RTSP connectivity
    env_file:
      - .env
